---
# permissions for end users to edit natpmps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: natpmp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: natpmp-controller
    app.kubernetes.io/part-of: natpmp-controller
    app.kubernetes.io/managed-by: kustomize
  name: natpmp-editor-role
rules:
  - apiGroups:
      - network.natpmp.jkoelker.github.io
    resources:
      - natpmps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - network.natpmp.jkoelker.github.io
    resources:
      - natpmps/status
    verbs:
      - get
